PLS WORKKKKKKKKKK

diff --git a/.github/workflows/multi-platform.yml b/.github/workflows/multi-platform.yml
--- a/.github/workflows/multi-platform.yml
+++ b/.github/workflows/multi-platform.yml
@@ -53,6 +53,12 @@ jobs:
       - uses: geode-sdk/build-geode-mod/combine@main
         id: build
 
+      - name: Debug
+        run: |
+          echo "Ref: ${{ github.ref }}"
+          echo "Build output: ${{ steps.build.outputs.build-output }}"
+          ls -la ${{ steps.build.outputs.build-output }} || echo "path not found"
+
       - uses: actions/upload-artifact@v4
         with:
           name: Build Output
@@ -66,7 +72,7 @@ jobs:
           name: Nightly Build
           prerelease: true
           body: Automated nightly build
-          files: ${{ steps.build.outputs.build-output }}
+          files: ${{ steps.build.outputs.build-output }}/*
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
@@ -78,6 +84,6 @@ jobs:
           name: Dev Nightly Build
           prerelease: true
           body: Automated dev nightly build
-          files: ${{ steps.build.outputs.build-output }}
+          files: ${{ steps.build.outputs.build-output }}/*
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
